### PR TITLE
chg:usr:Updated banchmarks to include application benchmarks

### PR DESCRIPTION
**Pull request by anurag2301**

### CODE REVIEW

**Comment by laszewsk** [comment]
report must be uploaded in the sp* repostiory

**Comment by ronak1182** [comment]
The final report is uploaded in the sp* repository. This is just a backup copy of the report.

**Comment by laszewsk** [comment]
Great. Thanks for following directions

**Comment by ronak1182** [comment]
The report was added to this repository so that in future anyone can have a look at the project and the report in one place.

**Pull request merged**
